### ISSUE TITLE
Localization via Custom Func

### ISSUE THREAD

**Issue by nzain** [SeriousM/WPFLocalizationExtension#100]
In #95 @MrCircuit posted a great idea:

> In general [...] one could think of a callback functionality (e.g. an assignable Func), that could be overwritten by particular implementations, e.g. by deriving from the LocExtension. This would leave space for different tasks. Please open a feature request, if this is what you could need in future.

Indeed, this would allow "cleaner" implementations for some things, that don't work out of the box. I would definitely use it to solve #95 cleaner than currently and investigate my other workarounds for applicability!

**Comment by MrCircuit** [comment]
### Discussion
What functionality do we need of this func and how should it be used?
****
I could imagine that this function wraps around the default functionality of the localization extension. This way, the basic text gets localized properly and the function can replace parts of it or overwrite it completely. This gives us two approaches:

1. Derive from LocExtension itself and hook into **FormatOutput**. One may call the base class function or not as needed. - This means no change in the current implementation :-)
2. Add a Func<string, CultureInfo, string> property to LocExtension that is called inside **FormatOutput**. This in turn calls for the developer to keep a reference to the particular affected instances of LocExtension so that it can be overwritten.
3. Add an attached property of type Func that could be checked by the LocExtension during **FormatOutput**.

**Comment by SeriousM** [comment]
Which of them can be used during design time? Design time is very important
aspect imho.
Am 05.05.2016 12:00 schrieb "Uwe Mayer" <notifications@github.com>:

**Comment by nzain** [comment]
Design Time is relevant for projects where localization happens within that same project. Personally, I'm not in this lucky position - global localization resources are shipped with the app (exe project) while 95% of the UI lives in separated module projects, where that resources are not available (no, I can't change this, unfortunately). So my design time always shows the "Missing Key: foo" thing, but I'm ok with that.

My use case: Support third-party localization combined with WPFLocalizationExtension (lex). Example: `System.Windows.Input.KeyGesture.GetDisplayStringForCulture(..)` _should_ localize keyboard shortcuts and typically you need some localized message (e.g. for a button's tooltip). We also have third-party libraries in use, that support some type of localization.

You say I could hook into `FormatOutput` without any modification. So this is already possible - how would I do this for the keyboard gesture tooltip? Override LocExtension and put a private MyLocExtension field into a custom control deriving from `TextBlock`?

- Tooltip text via standard lex with a localization key
- hard coded opening brace '('
- call `this.Gesture.GetDisplayStringForCulture` where Gesture is a DP or regular property
- hard coded closing brace ')'

If you could provide such an example (in your docs) it would probably help many others, too :+1: 
I'm ok with overriding some class to get custom behavior - no need for a Func then.

**Comment by SeriousM** [comment]
Closed due stall conversation
