### ISSUE TITLE
Support fo Design-Time Intellisense of String Resource file.

### ISSUE THREAD

**Issue by jstevenson72** [SeriousM/WPFLocalizationExtension#102]
I wondering if there is a way to reference your strings from the Resource file at Design Time in the xaml UI Designer?

For instance, in the following code:

![image](https://cloud.githubusercontent.com/assets/1573442/15028401/5bbeb1cc-120e-11e6-88db-557246d5b8d6.png)

So I would like to be able to start typing something like **Strings.Button** and have it respond siimilar to how it does in Code Behind with Strings.Button**_CreateSphere**.

![image](https://cloud.githubusercontent.com/assets/1573442/15028505/dea8da36-120e-11e6-99e1-69fd6ceddc80.png)

I tried a static reference, but although it compiles and runs the Localization Extension doesn't find the translation. i.e.

![image](https://cloud.githubusercontent.com/assets/1573442/15028519/ef63fd7e-120e-11e6-90e3-bb6b084b7e27.png)

Any thoughts?

**Comment by MrCircuit** [comment]
The only way is to write an own VS IntelliSense provider. One example can be found here:

* http://blog.robertgreyling.com/2010/05/sparksense-getting-started-wheres.html

With its code here:

* https://github.com/SparkViewEngine/SparkSense

**Comment by jstevenson72** [comment]
I don't think that would work because the localization extension doesn't reference the strings resource dictionary statically, does it?  It seems that some code would still need to change in this extension to be able to reference the strings like Inam trying...

**Comment by SeriousM** [comment]
This feature would be neat but it's very unlikely to be released. sorry.

**Comment by fernandreu** [comment]
Late to the party but, for anybody like me wondering about this and finding this issue, here is a workaround: create a separate file containing the property **names** (i.e. **not** the values) as constants, and reference those instead.

Something like this:
```csharp
public static class StringKeys
{
    // Using nameof() to reference the actual resource (in Strings.resx) will add you a little bit more of
    // static safety, as it forces it to exist
    public const string Button_CreateSphere = nameof(Strings.Button_CreateSphere);
}
```

Then, use it like:
```xaml
<Button Content="{lex:Loc {x:Static resources:StringKeys.Button_CreateSphere}}"/>
```

A bit more verbose, but you have IntelliSense available, plus your application won't even compile if the key does not exist.

The icing on the cake is to create a script that autogenerates the `StringKeys` class, so that you can run it whenever you change your resources file. This could also be a pre-build step of your project.
