### ISSUE TITLE
How to remove "key:"?

### ISSUE THREAD

**Issue by beachwalker** [SeriousM/WPFLocalizationExtension#103]
Hi guys,

I want to remove the output of "key:" in front of not translated (or not found) keys for the Release build.
I can't see easy extension point to achieve this. Any ideas/hints?

Thanks in advance,
Thomas

**Comment by 4PinsGigabit** [comment]
You could use the Resources.resx as a default value.
Here a simple example:
You have this resource files:
```
Resources.resx 
=> Name: TextYesNo Value: <blank>
Resources.de-DE.resx 
=> Name: TextYesNo Value: Ja / Nein
Resources.en-GB.resx
=> is empty
```
After program start you switch to German and you will see "Ja / Nein".
If you now switch to English WPFLocalizationExtension can not find the Key in en-GB and therefore will use the <blank> from Resources.resx.

**Limitations:**
The Key Values have at least to exist in the Resources.resx file otherwise you will see the "key:" output again.
You will have to set the language at program start so WPFLocalizationExtensions switches from default to the translation.

**Comment by beachwalker** [comment]
>The Key Values have at least to exist in the Resources.resx file otherwise you will see the "key:" output again.

That is exactly the problem. I want to remove that in case some texts come in dynamically and are (not yet) translated and want to switch off/on the "key: " for release/debug.

**Comment by 4PinsGigabit** [comment]
As mentioned in https://github.com/SeriousM/WPFLocalizationExtension/issues/92 there is a switch to disable the output:
> Regarding the Key: keyname issue: We only have an attached property named: LocalizeDictionary.OutputMissingKeys (default: true). This can mute the output of these errors.

Maybe I've overlooked something, but setting it to false does not work for me.
`lex:LocalizeDictionary.OutputMissingKeys="False"`

**Comment by xmedeko** [comment]
I have peered into the code and cannot find any place, where the `OutputMissingKeys` is used. It should be plugged somewhere or removed, if it is not used.
