### ISSUE TITLE
Make ResxLocalizationProvider possible to subclass

### ISSUE THREAD

**Issue by xmedeko** [SeriousM/WPFLocalizationExtension#126]
Currently, the `ResxLocalizationProvider` is not possible to subclass since it has private constructor and uses static readonly `Instance`. When I need to change some behaviour, I have to copy & paste whole code.

I think it would be enough to make constructor protected and define set for the `Instance`. If you agree, I can publish a PR for that.

My use case is, that I have a multiple assembly, multiple dictionary project and want to:
- Specify some shortcuts, e.g. instead of `MyAssembly2:MyDictionary3:myKey` I want to write only `MA2:MD3:myKey`.
- Search multiple dictionaries, e.g. in the XAML is just `myKey` and I want to search `MyAssembly1` and `MyAssembly2` for that key (with the default dictionary).

**Comment by SeriousM** [comment]
Oh, that sounds like a valid usecase! A PR would be very appreciated!
Please declare the setter method as a protected virtual on
the ResxLocalizationProvider so that it's a privilege for inheritors and
its not soo exposed.
Could you have a look at #125 too? I guess it's easy to fix.
Thank you so much!


Am 22.12.2017 20:29 schrieb "Ondrej Medek" <notifications@github.com>:

Currently, the ResxLocalizationProvider is not possible to subclass since
it has private constructor and uses static readonly Instance. When I need
to change some behaviour, I have to copy & paste whole code.

I think it would be enough to make constructor protected and define set for
the Instance. If you agree, I can publish a PR for that.

My use case is, that I have a multiple assembly, multiple dictionary
project and want to:

   - Specify some shortcuts, e.g. instead of MyAssembly2:MyDictionary3:myKey
   I want to write only MA2:MD3:myKey.
   - Search multiple dictionaries, e.g. in the XAML is just myKey and I
   want to search MyAssembly1 and MyAssembly2 for that key (with the
   default dictionary).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SeriousM/WPFLocalizationExtension/issues/126>, or mute
the thread
