### ISSUE TITLE
LocTextExtension.Assembly is obsolete

### ISSUE THREAD

**Issue by Lutzeslife** [SeriousM/WPFLocalizationExtension#43]
Hello,

i want to know what kind of changes i should excepted when i us the Asembly property of LocTextExtension which is obsolete? Is there any plan to change the property?

Best regards
Daniel

**Comment by MrCircuit** [comment]
**Open discussion:** How should we continue with Assembly and Dict properties? In fact, they are not needed any more and do not work together with custom resource providers. Otherwise they do not interfere in a bad way and keep up the support of legacy applications.

**Comment by SeriousM** [comment]
Well, the common property is the `key`. For the resource file provider we
could add them to a derivation and enforce the usage via an generic
interface. On the other hand we can just drop assembly and dict property
and work with the composite key like "x:y:z".
We don't need to care too much for legacy code because the backend was
never the target environment for the extension and we always recommended
the usage of the composite key.

Agree with the second solution?

**Comment by MrCircuit** [comment]
Vote for 2nd

**Comment by SeriousM** [comment]
we will drop the assembly and dict key with the next version
