### ISSUE TITLE
Unit Test and Localization and thread issues

### ISSUE THREAD

**Issue by HartlD** [SeriousM/WPFLocalizationExtension#56]
Bevor I had updated the Localization Extension, I got the Test result failure that Localization is used by a
another thread,....

By the lates version my unit Tests->RunAll -> Hanging->no response i have to Cancel all tests.

**Comment by MrCircuit** [comment]
Can you share a simple test scenario that reproduces the error (e.g. by forking and extending one of our tests?)

**Comment by KristianKuhlmann** [comment]
Hello MrCircuit, 
we use WPFLocalizeExtension excessively and are experiencing the exact same and other similar threading issues as reported in this bug report. 

Currently it is not possible to change the LocalizeDictionary.Instance.Culture from another thread as the main thread. This will cause the Disptacher to block. The application hangs (seems to lock) at WPFLocalizeExtension.Engine.LocalizeDictionary.GetIsInDesignMode() at Line 1022 on Dispatcher.Invoke. 
To reproduce this issue I can provide a little example. How can I upload this here?

I will submit a possible fix for this into your repo with a pull request.

Additionally i will submit a possible fix to issue when concurrently resolving from several threads. This issue is also shown by the submitted example.

Kind regards,
Kristian
