### ISSUE TITLE
Forum or SO tag

### ISSUE THREAD

**Issue by xmedeko** [SeriousM/WPFLocalizationExtension#57]
Hi, I miss some place, like forum, to discuss proper use of WPFLocalizationExtension. Or an "official"  StackOverflow tag - now the SO topics about WPFLocalizationExtension are sometimes tricky to find. (Some people use WPFLocalizationExtension, others WPFLocalizeExtension, ...). If you decide to create SOI tag, just put it into README.md.

**Comment by SeriousM** [comment]
Hi!

I don't know which tags you ment which are used already, but its neither http://stackoverflow.com/questions/tagged/WPFLocalizationExtension or http://stackoverflow.com/questions/tagged/WPFLocalizeExtension.

I agree, a SO tag would be nice, but we wouldn't monitor it because of the missing time.
@MrCircuit and I have already hard times to keep up with the questions and issues.

What would help enormously is someone that writes a documentation in a markdown format because our wiki pages are quite odd and outdated.

Would you help us out?

**Comment by xmedeko** [comment]
No SO tag for WPFLocalizationExtension exists yet. I mean some people call it WPFLocalizationExtension, others WPFLocalizeExtension. It's not easy to do full text search to find relevant topics. I propose to create SO tag and write it to the README.md, so as people will know where to discuss problems and how to tag new topics.

I can help with wiki - just copy and paste old documentation. But do not I have time to do it a once. Maybe one chapter now, another later, and so on ...
