### ISSUE TITLE
Error 4 when using WPFLocalizationExtension inside a style 

### ISSUE THREAD

**Issue by steA** [SeriousM/WPFLocalizationExtension#96]
Hi all,

I have a similar problem as the one described in this thread https://github.com/SeriousM/WPFLocalizationExtension/issues/55
I have uploaded an example project here https://github.com/steA/LocExtensionTest

Basically I am getting the following error:

`System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'Label' (Name=''); target property is 'Parent' (type 'DependencyObject')`

If I remove the `Content="{lex:LocText UI_Search}"` from the label inside the file `LocExtensionView.xaml` the error doesn't show up anymore.

Can you help me?

**Comment by MrCircuit** [comment]
These errors are sometimes hard to find. I suggest to view this blog on how to debug such messages:

https://spin.atomicobject.com/2013/12/11/wpf-data-binding-debug/

Nevertheless, in your particular example, the problem is as follows (as far as I understood): The WPF Binding engine starts after app start and handles our internal Binding to the Parent property of a FrameworkElement. But the binding is evaluated before the visual tree is completed, which means that the resource you defined is still not applied to the target control. Later, when it is attached, the binding gets somehow healed and everything is OK again (I don't really know much about the internals of this process).

To solve the issue in your case: Feed the extension with information that stops it from continuous search of parents in the visual tree. Which means: use the lex:ResxLocalizationProvider.DefaultAssembly and lex:ResxLocalizationProvider.DefaultDictionary directly at the level of the resource.

**Comment by steA** [comment]
Thank you!
